permalink: "/:title.html"
url: https://kirbysayshi.github.com/broad-phase-bng
name: Broad Phase Collision Detection
description: Draft location for collision detection articles
exclude: ['node_modules']
