pygments: true
permalink: /:title.html
baseurl: /broad-phase-bng
name: Broad Phase Collision Detection
description: Draft location for collision detection articles
markdown: maruku
exclude: ['node_modules']
